### PR TITLE
feat: reduce bundle size with code splitting

### PR DESCRIPTION
**Pull request by michielmetcake**
# Context
The current implementation introduces unnecessary dependencies into the `_app` or `_document`. Because  1 function is used to support both. This results in having code that's needed for the server in the client as mentioned in [this](https://github.com/garronej/tss-react/issues/147) issue. 

# What's done?
The API is backwards compatible to support current usage
The functions `withAppEmotionCache` and `augmentDocumentWithEmotionCache` are split into separate files so they could be implemented individually. This enables to only import and use the code related to them in the files where it's actually needed. And reduces the `_app` bundle size by over 50%.

# Result
Suggested implementation `_app` bundle size:
image

Current implementation `_app` bundle size:
image

### CODE REVIEW

**Comment by michielmetcake** [comment]
I also wanted to update the docs, but I can't find them. I can also update them if you share the docs with me @garronej .

**Comment by garronej** [comment]
Hey, thank you verry much for the PR!  
I want to explore the lazy import route before merging this though https://github.com/garronej/tss-react/pull/149 as it would not require any refactor.

**Comment by michielmetcake** [comment]
> Hey, thank you verry much for the PR!  
> 
> I want to explore the lazy import route before merging this though https://github.com/garronej/tss-react/pull/149 as it would not require any refactor.  

I checked that as wel. But for me it still included the next/server packages in the bundle. I think those two functions are needed. But please surprise me 👍🏼

**Comment by garronej** [comment]
Well thank you very much for your work.  
Reducing the bundle size by that mutch is a big step forward.  
I'm closing since #149 fixes it.

**Pull request closed without merging**
