### PR TITLE
fix: add code-splitting and ssr-code-split app

### PR DESCRIPTION
**Pull request by michielmetcake**
# Context
The current implementation introduces unnecessary dependencies into the `_app` or `_document`. Because  1 function is used to support both. This results in having code that's needed for the server in the client as mentioned in [this](https://github.com/garronej/tss-react/issues/147) issue. 
Unfortunately https://github.com/garronej/tss-react/pull/149 didn't reduce the bundle size significantly. So this PR and new approach for adding the cache is needed.

# What's done?
The API is backwards compatible to support current usage
The functions `withAppEmotionCache` and `augmentDocumentWithEmotionCache` are split into separate files so they could be implemented individually. This enables to only import and use the code related to them in the files where it's actually needed. And reduces the `_app` bundle size by over 50%.

# Result
Suggested implementation `_app` bundle size:
image

Current implementation `_app` bundle size:
image

### CODE REVIEW

**Comment by michielmetcake** [comment]
I've added the analyze script in both apps so they're easier to compare.

**Comment by garronej** [comment]
Thank you for your effort, I'm trying it out

**Comment by garronej** [comment]
Ok @michielmetcake,  
My bad,  
Your implementation does indeed drastically reduce the bundle size.  
I would like to rework the API but I released a cadidate that include your fix that you can use right now:  4.6.2-rc.1  

Thanks for your work!

**Comment by garronej** [comment]
Fixed in 4.7 by dependency injection: Fixed in 4.7 by dependency injection: https://docs.tss-react.dev/migration-guides/v4.6-greater-than-v4.7  

Thanks for your work!

**Pull request closed without merging**
