### PR TITLE
New improved makeStyles implementation

### PR DESCRIPTION
**Pull request by olee**
New improved `makeStyles` implementation offering various benefits:
- Automatic label assignment
- Easier and safer ref usage
- Better performance for static styles

This PR contains the improvements outlined in #26 and some more

### CODE REVIEW

**Comment by garronej** [comment]
The new API for nested selector works great with `makeStyles`. Need some more work for `withStyles`.

**Comment by olee** [comment]
@garronej so what do you think needs to be worked on for this to be merged?
I've been using this new version of `makeStyles` in production quite a while now and I can confirm it works flawlessly 👍 
Especially the performance improvement by adding useMemo around the whole style calculation when no props / params are passed to useStyles is nice to have.

**Comment by garronej** [comment]
> so what do you think needs to be worked on for this to be merged?

First of all thank you very for your work, you have very good ideas and the implementation you offered was almost there.  
That said, you have to understand that this PR can't be merged. If you want your code to actually be included instead of being taken as a suggestion you must split your changes into different commits with minimal diff that can be discussed individually.  
I can give you credit however for the commit based on changes you suggested. For that you will need to open a rebased PR.

> Especially the performance improvement by adding useMemo around the whole style calculation 

This is indeed a nice improvement! It's [in the code](https://github.com/garronej/tss-react/commit/625b868320f7d58b6d204b03c9546d5a8385f3ad) since v2.0.4. 
I had to iterate over what you had done a little bit though. 
In your implementation, passing `params` to `useStyles(params)` prevent the memoization. 
If users do `const { classes } = useStyles({ "color": "red" })` the styles are re-computed every render
because the reference of `{ "color": "red" }` changes every render.  

The labelling is already in production, see documentation [here](https://github.com/garronej/tss-react#labeling).  
I took the liberty to use `label` instead of `name`.  

Regarding the new ref API, with some minor tweak from the implementation you suggested, the API [meets my type-safery requirements](https://github.com/garronej/tss-react/commit/cafca398e26341e7ee23809a2e1ea78e26fc8b97#diff-df0cfa0d21a58179604f5639d6490e6c0fdde3145376eaf54bcc566d7eee63dc).  
[Here is the branch](https://github.com/garronej/tss-react/tree/new_api_for_nested_selector) where the ongoing work is being done.  
What stopping me from merging is that I can't make the `ref` API work with [withStyle](https://github.com/garronej/tss-react/tree/new_api_for_nested_selector#withstyles), I don't know if it's even possible. I haven't decided what I am going to do about it yet. 

Best

**Comment by olee** [comment]
Thanks for the feedback.

I can agree that there were a lot of issues grouped together in that single PR so it's a good idea to split this up.

As for the useMemo-optimization, I already created [a separate issue](https://github.com/garronej/tss-react/issues/39) because there are some problems with your implementation.

Also, could you explain why you used `label` instead of `name`? The `name` option is the same as is used in material-ui and it would make transitioning a lot easier I think. 
However, I could imagine you might have done it in consideration for users who use this library coming not from material-ui but emotion instead where it is named `label`?
Personally I would prefer to actually change it to `name` (I think it would be fine considering it was just added recently), but I suppose it can be kept as `label` as well.

To make it easier to get feedback on such new APIs prior to having them in full releasing and having to deal with breaking changes, maybe you could open PRs yourself for such things to take in feedback or release these changes initially as release-candidates to npm? We could do the same with the new API proposed in this PR as well I think 🤔 

As for the branch you created: It's good to see that you want to adapt the new API as well and I hope we can work on this together to get this done. I will try to find some time these days to look into it and also try to figure out solutions for the withStyles compatibility.

**Comment by garronej** [comment]
Yes you are right I should should have consulted you before putting things in productions. I have to update [ts-ci](https://github.com/garronej/ts-ci) workflow to support the release of beta version.  
This is something that I feel the need for more and more.  

Sorry about opting for `label` in place of `name`. You made me aware of [the `label` property in `emotion`](https://emotion.sh/docs/labels). I though it was a good idea to keep the same terminology but it's true that our user are more familiar with `mui` than they are with `emotion`.  I was't aware of [that](https://mui.com/styles/api/#makestyles-styles-options-hook).  
Anyway we will have to release a new major release coming out soon hopefully so we will be able to rollback, we will discuss.

**Comment by olee** [comment]
No need to apologise :D
Also good work on providing the option for alpha builds now 👍 

As said, I will try to update the PR based on your branch once I got some time again

**Comment by garronej** [comment]
The work done in this PR have been reported [here](https://github.com/garronej/tss-react/pull/40).  
I close this, meet you there.  
@olee I will make sure to give you credit before we release this feature.

**Pull request closed without merging**
