### PR TITLE
Allow nested selectors

### PR DESCRIPTION
**Pull request by jsakas**
@garronej this seems to work, by calling emotion `css` function twice - but it breaks the types.

Screen Shot 2021-08-18 at 1 46 04 PM

### CODE REVIEW

**Comment by jsakas** [comment]
Actually if I change:

```typescript
            getCssObjectOrCssObject:
                | ((
                      theme: Theme,
                      params: Params,
                      classes: Record<Key, string>,    // <-- here
                  ) => Record<Key, CSSObject>)
                | Record<Key, CSSObject>,
```

to:

```typescript
            getCssObjectOrCssObject:
                | ((
                      theme: Theme,
                      params: Params,
                      classes: any,
                  ) => Record<Key, CSSObject>)
                | Record<Key, CSSObject>,
```

But I am not totally sure why that happens. Also any seems like not the right choice here but it does get it working.

**Comment by garronej** [comment]
Damn,  
I though it was the runtime that would be hard to get working but it's actually the typings that turn out to be a problem. 
I got the `classes` parameter to be inferred as `Record<string, string>` but I am still failing to to get it as `Record<"el1" | "el2", string>`...  
Good job on the implementation though.

**Comment by garronej** [comment]
I am very disappointed 😞   
I think it's a no go with the current state of typescript.  
Trying to think of another API...

**Comment by jsakas** [comment]
> I am very disappointed 😞
> I think it's a no go with the current state of typescript.
> Trying to think of another API...

Calling `css` function twice isn't really ideal either. I'm not sure if there is a performance hit, but it seems hacky. 

I am going to run this in the meantime, until a better API emerges.

**Comment by jsakas** [comment]
@garronej also, I pushed up the change from `any` to `Record<string, string>` since it's at least a slight improvement. Even without the typings on the `classes` that come back in `useStyles` the work might still be useful to some 🤷🏻‍♂️ 

You might still consider a merge and then a minor version bump later in the case of a better API.

**Comment by garronej** [comment]
Hold on a minute, I want to know what you think about this

**Comment by garronej** [comment]
What do you think of that:  

image

It's less sexy but also less voodooish and type safe...

**Comment by jsakas** [comment]
Seems fine to me if it gets the job done!

**Comment by garronej** [comment]
I test it and release it in the next hour.  
Thank you very much for your involvement, it helps a lot

**Comment by garronej** [comment]
I will merge even if I override it. This way you'll appear in the contributor list.

**Pull request merged**
